default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.18
    hooks:
      - id: uv-sync
      - id: uv-export
        args:
          [
            "-o",
            "requirements.txt",
            "-q",
            "--no-dev",
            "--no-emit-project",
            "--no-hashes",
          ]
      - id: uv-export
        args:
          [
            "-o",
            "requirements-dev.txt",
            "-q",
            "--no-emit-project",
            "--no-hashes",
          ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-format
      - id: ruff-check
      - id: ruff-format
